name: dev_toolkit
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - ipython
  - python-dotenv
  - requests
  - beautifulsoup4
  - pdfplumber
  - httpx
  - whisper
  - ollama
  - openai
  - notebook           
  - ipykernel          
  - pip:
      - openai
      - ollama
      - whisper
      - python-dotenv
      - httpx
      - pdfplumber
      - beautifulsoup4
